# Generated by Django 2.0.6 on 2018-06-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('address', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('flyer', models.ImageField(upload_to='flyers')),
                ('event_site', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('page', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('letter', models.FileField(upload_to='newsletters')),
            ],
        ),
    ]
