# Generated by Django 2.0.6 on 2018-06-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stevie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='event_site',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='flyer',
            field=models.ImageField(blank=True, null=True, upload_to='flyers'),
        ),
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='letter',
            field=models.FileField(blank=True, null=True, upload_to='newsletters'),
        ),
        migrations.AlterField(
            model_name='post',
            name='venue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
