# Generated by Django 2.0.6 on 2018-07-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stevie', '0002_auto_20180630_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='page',
            field=models.CharField(choices=[('HM', 'Home'), ('VN', 'Venues'), ('CL', 'Calendar'), ('NL', 'Newsletter')], max_length=2),
        ),
    ]
