# Generated by Django 2.0.6 on 2018-07-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stevie', '0003_auto_20180702_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='page',
            field=models.CharField(choices=[('HM', 'Home'), ('VN', 'Venues'), ('CL', 'Calendar'), ('NL', 'Newsletter'), ('SB', 'Sidebar'), ('CI', 'Contact Info')], max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
