# Generated by Django 2.0.6 on 2018-08-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stevie', '0004_auto_20180705_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='page',
            field=models.CharField(choices=[('HM', 'Home'), ('VN', 'Venues'), ('CL', 'Calendar'), ('ES', 'esSense'), ('SB', 'Sidebar'), ('CI', 'Contact Info'), ('NN', "NEWS'n NOTES")], max_length=2),
        ),
    ]
